"""
This file is used to perform automated comparisons between the RPD files generated by the EnergyPlus RPD utility and the
expected RPD files for the 229P test suite. Files must pass validation against the 0.1.7 version of the 229 schema. Any
invalid files will end the script execution.

Because the RPD files contain many arrays where the order of the elements does not matter, this script first attempts to
map the objects in the generated RPD files to the corresponding objects in the expected RPD files based on varying
methodology depending on the object type. For example, surfaces are mapped based on the classification, adjacent_to, and
the zone the surface is in (while accounting for the fact that interior wall surfaces may be defined in either the same
zone as the reference surface or in the adjacent zone with azimuth rotated by 180 degrees).

This script will print out the mapping of objects in the expected RPD files to the generated RPD files. If the mapping
is unsuccessful or inaccurate, you are likely to see unexpected behavior. For that reason, first verify that the mapping
is correct. If mapping is incorrect, that may be an indication that the associated objects in the RPD files are not
being generated correctly or that the mapping logic needs to be improved for a scenario that was not accounted for.
"""


if __name__ == "__main__":
    from pathlib import Path
    from rpdvalidator import validate_rpd

    from energyplus_rpd.test.full_rpd_test_helper.rpd_tester.perform_comparison import run_comparison_for_all_tests

    test_dir = Path(__file__).parent / "test_files_229_FSEC"

    # Validate the generated RPD files against the 0.1.7 version of the 229 schema
    for test_case_dir in test_dir.iterdir():
        if not test_case_dir.is_dir():
            continue

        test = test_case_dir.name
        print("Validating FSEC test case:", test)
        generated_json_file = next(
            (f for f in test_case_dir.iterdir() if f.suffix == ".rpd"), None
        )
        validate_rpd(generated_json_file, "0.1.7")

    # If validation passes, perform automated comparisons between the generated RPD files and the expected RPD files
    run_comparison_for_all_tests(test_dir)

    test_dir = Path(__file__).parent / "test_files_229_PSD"

    # Validate the generated RPD files against the 0.1.7 version of the 229 schema
    for test_case_dir in test_dir.iterdir():
        if not test_case_dir.is_dir():
            continue

        test = test_case_dir.name
        print("Validating PSD test case:", test)
        generated_json_file = next(
            (f for f in test_case_dir.iterdir() if f.suffix == ".rpd"), None
        )
        validate_rpd(generated_json_file, "0.1.7")

    # If validation passes, perform automated comparisons between the generated RPD files and the expected RPD files
    run_comparison_for_all_tests(test_dir)
