from pathlib import Path
from tempfile import mkdtemp
from unittest import TestCase

from energyplus_rpd.compliance_parameter_handler import ComplianceParameterHandler


class TestComplianceParameterHandler(TestCase):

    def setUp(self) -> None:
        self.run_dir_path = Path(mkdtemp())
        input_file_path = self.run_dir_path / 'in.epJSON'
        self.cph = ComplianceParameterHandler(input_file_path)

    def test_init(self):
        input_file_path = self.run_dir_path / 'in.epJSON'
        cph = ComplianceParameterHandler(input_file_path)
        elements = cph.compliance_group_element
        self.assertEqual(elements['building'], {'building_open_schedule': ''})
        self.assertEqual(cph.cp_empty_file_path.name, 'in.comp-param-empty.json')
        self.assertEqual(cph.cp_file_path.name, 'in.comp-param.json')

    def test_add_compliance_parameters(self):
        return_dict = {}
        self.cph.add_compliance_parameters('', return_dict)
        self.assertEqual(return_dict, {})

        return_dict = {}
        self.cph.add_compliance_parameters('building', return_dict)
        self.assertEqual(return_dict, {'building_open_schedule': ''})

        return_dict = {}
        self.cph.add_compliance_parameters('subsurfaces', return_dict)
        expected = ({'subclassification': 'OTHER',
                     'is_operable': False,
                     'has_open_sensor': False,
                     'framing_type': 'ALUMINUM_WITH_BREAK',
                     'has_manual_interior_shades': False,
                     'status_type': 'NEW'})
        self.assertEqual(return_dict, expected)

    def test_mirror_nested(self):
        original_dict = {'id': 'CORE_ZN ZN PSZ-AC-1',
                         'heating_system': {'id': 'CORE_ZN ZN PSZ-AC-1-heating', 'design_capacity': 9209.104,
                                            'type': 'HEAT_PUMP', 'energy_source_type': 'ELECTRICITY',
                                            'rated_capacity': 9221.21, 'oversizing_factor': 1.000000434352977,
                                            'is_sized_based_on_design_day': True, 'heating_coil_setpoint': 46.8,
                                            'efficiency_metric_values': [7.53, 6.84],
                                            'efficiency_metric_types': ['HEATING_SEASONAL_PERFORMANCE_FACTOR',
                                                                        'HEATING_SEASONAL_PERFORMANCE_FACTOR_2'],
                                            'heatpump_low_shutoff_temperature': -12.2},
                         'fan_system': {'id': 'CORE_ZN ZN PSZ-AC-1 FAN-fansystem',
                                        'minimum_airflow': 370.90000000000003,
                                        'minimum_outdoor_airflow': 64.60000000000001, 'fan_control': 'CONSTANT',
                                        'supply_fans': [{'id': 'CORE_ZN ZN PSZ-AC-1 FAN', 'design_airflow': 0.37,
                                                         'is_airflow_sized_based_on_design_day': True,
                                                         'design_electric_power': 415.54,
                                                         'design_pressure_rise': 622.72, 'total_efficiency': 0.56,
                                                         'motor_efficiency': 0.85,
                                                         'motor_heat_to_airflow_fraction': 1.0,
                                                         'motor_heat_to_zone_fraction': 0.0,
                                                         'motor_location_zone': 'N/A',
                                                         'specification_method': 'SIMPLE'}]}}
        result_dict = {}
        self.cph.mirror_nested(original_dict, result_dict)

        expected = {'fan_system': {'id': 'CORE_ZN ZN PSZ-AC-1 FAN-fansystem',
                                   'supply_fans': [{'id': 'CORE_ZN ZN PSZ-AC-1 FAN'}]},
                    'heating_system': {'id': 'CORE_ZN ZN PSZ-AC-1-heating'}, 'id': 'CORE_ZN ZN PSZ-AC-1'}

        self.assertEqual(result_dict, expected)

    def test_create_empty_compliance_json(self):
        # based on SmallOffice-90.1-2013-ASHRAE 169-2013-5B-no_user_data-remove_transformer.epJSON
        # but extensively edited
        json_dict = {
            "id": "project description root",
            "notes": "generated by createRulesetProjectDescription from EnergyPlus",
            "output_format_type": "OUTPUT_SCHEMA_ASHRAE901_2019",
            "data_timestamp": "2024-08-16T20:10Z",
            "data_version": 1,
            "ruleset_model_descriptions": [
                {
                    "id": "Only model description",
                    "notes": "this file contains only a single model description",
                    "type": "PROPOSED",
                    "buildings": [
                        {
                            "id": "-SmallOffice-ASHRAE 169-2013-5B created: 2022-05-03 14:28:47 -0700",
                            "notes": "this file contains only a single building",
                            "building_open_schedule": "always_1",
                            "has_site_shading": False,
                            "building_segments": [
                                {
                                    "id": "segment 1",
                                    "heating_ventilating_air_conditioning_systems": [
                                        {
                                            "id": "CORE_ZN ZN PSZ-AC-1",
                                            "heating_system": {
                                                "id": "CORE_ZN ZN PSZ-AC-1-heating",
                                                "design_capacity": 9209.104,
                                                "type": "HEAT_PUMP",
                                                "energy_source_type": "ELECTRICITY",
                                                "rated_capacity": 9221.21,
                                                "oversizing_factor": 1.000000434352977,
                                                "is_sized_based_on_design_day": True,
                                                "heating_coil_setpoint": 46.8,
                                                "efficiency_metric_values": [
                                                    7.53,
                                                    6.84
                                                ],
                                                "efficiency_metric_types": [
                                                    "HEATING_SEASONAL_PERFORMANCE_FACTOR",
                                                    "HEATING_SEASONAL_PERFORMANCE_FACTOR_2"
                                                ],
                                                "heatpump_low_shutoff_temperature": -12.2
                                            },
                                            "fan_system": {
                                                "id": "CORE_ZN ZN PSZ-AC-1 FAN-fansystem",
                                                "minimum_airflow": 370.90000000000003,
                                                "minimum_outdoor_airflow": 64.60000000000001,
                                                "fan_control": "CONSTANT",
                                                "supply_fans": [
                                                    {
                                                        "id": "CORE_ZN ZN PSZ-AC-1 FAN",
                                                        "design_airflow": 0.37,
                                                        "is_airflow_sized_based_on_design_day": True,
                                                        "design_electric_power": 415.54,
                                                        "design_pressure_rise": 622.72,
                                                        "total_efficiency": 0.56,
                                                        "motor_efficiency": 0.85,
                                                        "motor_heat_to_airflow_fraction": 1.0,
                                                        "motor_heat_to_zone_fraction": 0.0,
                                                        "motor_location_zone": "N/A",
                                                        "specification_method": "SIMPLE"
                                                    }
                                                ]
                                            }
                                        },
                                    ],
                                    "zones": [
                                        {
                                            "id": "ATTIC ZN",
                                            "volume": 720.19,
                                            "surfaces": [
                                                {
                                                    "id": "ATTIC_FLOOR_CORE",
                                                    "classification": "FLOOR",
                                                    "area": 149.66,
                                                    "tilt": 180.0,
                                                    "azimuth": 0.0,
                                                    "adjacent_to": "INTERIOR",
                                                    "does_cast_shade": True,
                                                    "adjacent_zone": "CORE_ZN ZN",
                                                    "construction": {
                                                        "id": "Typical Wood Joist Attic Floor R-47.62 1",
                                                        "surface_construction_input_option": "LAYERS",
                                                        "primary_layers": [
                                                            {
                                                                "id": "Typical Insulation R-45.98 1",
                                                                "r_value": 8.09838632642688
                                                            },
                                                            {
                                                                "id": "5/8 in. Gypsum Board",
                                                                "thickness": 0.0159,
                                                                "thermal_conductivity": 0.159999999999999,
                                                                "density": 799.999999999999,
                                                                "specific_heat": 1090
                                                            }
                                                        ],
                                                        "u_factor": 0.118
                                                    }
                                                },
                                            ],
                                            "infiltration": {
                                                "id": "ATTIC INFILTRATION",
                                                "modeling_method": "WEATHER_DRIVEN",
                                                "algorithm_name": "ZoneInfiltration",
                                                "flow_rate": 0.2,
                                                "multiplier_schedule": "ALWAYS ON"
                                            },
                                            "spaces": [
                                                {
                                                    "id": "ATTIC_SPACE",
                                                    "floor_area": 567.98,
                                                    "number_of_occupants": 0,
                                                    "lighting_space_type": "STORAGE_ROOM_LARGE",
                                                    "ventilation_space_type":
                                                        "OFFICE_BUILDINGS_OCCUPIABLE_STORAGE_ROOMS_FOR_DRY_MATERIALS",
                                                    "service_water_heating_space_type": "OFFICE"
                                                }
                                            ]
                                        },
                                    ]
                                }
                            ],
                            "exterior_lighting": [
                                {
                                    "id": "NONDIMMING EXTERIOR LIGHTS DEF",
                                    "power": 50.7,
                                    "multiplier_schedule": "uses_astronomical_clock_not_schedule"
                                },
                            ]
                        }
                    ],
                    "chillers": [],
                    "boilers": [],
                    "heat_rejections": [],
                    "pumps": [
                        {
                            "id": "MAIN SERVICE WATER LOOP WATER MAINS PRESSURE DRIVEN",
                            "loop_or_piping": "MAIN SERVICE WATER LOOP",
                            "specification_method": "SIMPLE",
                            "design_electric_power": 0.0,
                            "design_head": 0.0,
                            "motor_efficiency": 0.7,
                            "speed_control": "VARIABLE_SPEED",
                            "design_flow": 0.004,
                            "is_flow_sized_based_on_design_day": True
                        }
                    ],
                    "fluid_loops": [],
                    "output": {
                        "id": "output_1",
                        "output_instance": {
                            "id": "output_instance_1",
                            "ruleset_model_type": "PROPOSED",
                            "rotation_angle": 0,
                            "unmet_load_hours": 34.83,
                            "unmet_load_hours_heating": 22.67,
                            "unmet_occupied_load_hours_heating": 22.67,
                            "unmet_load_hours_cooling": 12.17,
                            "unmet_occupied_load_hours_cooling": 12.17,
                            "annual_source_results": [
                                {
                                    "id": "source_results_ELECTRICITY",
                                    "energy_source": "ELECTRICITY",
                                    "annual_consumption": 179.04,
                                    "annual_demand": 21760.95,
                                    "annual_cost": -1.0
                                },
                            ],
                            "building_peak_cooling_load": -1,
                            "annual_end_use_results": [
                                {
                                    "id": "end_use_ELECTRICITY-Cooling",
                                    "type": "SPACE_COOLING",
                                    "energy_source": "ELECTRICITY",
                                    "annual_site_energy_use": 16.14,
                                    "annual_site_coincident_demand": 0.0,
                                    "annual_site_non_coincident_demand": 6339.64,
                                    "is_regulated": True
                                },
                            ]
                        },
                        "performance_cost_index": -1.0,
                        "baseline_building_unregulated_energy_cost": -1.0,
                        "baseline_building_regulated_energy_cost": -1.0,
                        "baseline_building_performance_energy_cost": -1.0,
                        "total_area_weighted_building_performance_factor": -1.0,
                        "performance_cost_index_target": -1.0,
                        "total_proposed_building_energy_cost_including_renewable_energy": -1.0,
                        "total_proposed_building_energy_cost_excluding_renewable_energy": -1.0,
                        "percent_renewable_energy_savings": -1.0
                    },
                }
            ],
            "weather": {
                "file_name": "Denver Centennial  Golden   Nr CO USA TMY3 WMO#=724666",
                "data_source_type": "OTHER",
                "climate_zone": "CZ5B",
                "cooling_design_day_type": "COOLING_0_4",
                "heating_design_day_type": "HEATING_99_6"
            },
            "calendar": {
                "notes": "name environment: RUN PERIOD 1",
                "day_of_week_for_january_1": "SUNDAY",
                "is_leap_year": False,
                "has_daylight_saving_time": True
            }
        }

        result = self.cph.create_empty_compliance_json(json_dict)

        expected = \
            {'id': 'project description root', 'ruleset_model_descriptions': [
                {'type': 'PROPOSED', 'measured_infiltration_pressure_difference': 0,
                 'is_measured_infiltration_based_on_test': False,
                 'site_zone_type': 'ZONE_4_HIGH_ACTIVITY_COMMERCIAL',
                 'id': 'Only model description',
                 'buildings': [
                     {'id': '-SmallOffice-ASHRAE 169-2013-5B created: 2022-05-03 14:28:47 -0700',
                      'building_segments': [
                          {'is_all_new': True,
                           'area_type_vertical_fenestration': 'OFFICE_MEDIUM',
                           'lighting_building_area_type': 'OFFICE',
                           'area_type_heating_ventilating_air_conditioning_system': 'OTHER_NON_RESIDENTIAL',
                           'id': 'segment 1',
                           'heating_ventilating_air_conditioning_systems': [
                               {'status_type': 'NEW',
                                'id': 'CORE_ZN ZN PSZ-AC-1',
                                'heating_system':
                                    {'id': 'CORE_ZN ZN PSZ-AC-1-heating'},
                                'fan_system': {'id': 'CORE_ZN ZN PSZ-AC-1 FAN-fansystem',
                                               'supply_fans': [
                                                   {'id': 'CORE_ZN ZN PSZ-AC-1 FAN'}]}}],
                           'zones': [
                               {'conditioning_type': 'HEATED_AND_COOLED',
                                'aggregation_factor': 1,
                                'id': 'ATTIC ZN',
                                'surfaces': [
                                    {'status_type': 'NEW',
                                     'id': 'ATTIC_FLOOR_CORE',
                                     'construction':
                                         {'classification': 'STEEL_FRAMED',
                                          'id': 'Typical Wood Joist Attic Floor R-47.62 1',
                                          'primary_layers': [
                                              {'id': 'Typical Insulation R-45.98 1'},
                                              {'id': '5/8 in. Gypsum Board'}]}}],
                                'infiltration':
                                    {'measured_air_leakage_rate': 0,
                                     'id': 'ATTIC INFILTRATION'},
                                'spaces': [
                                    {'status_type': 'NEW',
                                     'function': 'OTHER',
                                     'id': 'ATTIC_SPACE'}]}]}],
                      'exterior_lighting': [
                          {'id': 'NONDIMMING EXTERIOR LIGHTS DEF'}]}],
                 'pumps': [
                     {'motor_nameplate_power': 0.0,
                      'impeller_efficiency': 0.0,
                      'id': 'MAIN SERVICE WATER LOOP WATER MAINS PRESSURE DRIVEN'}],
                 'output': {'id': 'output_1',
                            'output_instance': {
                                'id': 'output_instance_1',
                                'annual_source_results': [
                                    {
                                        'id': 'source_results_ELECTRICITY'}],
                                'annual_end_use_results': [
                                    {
                                        'id': 'end_use_ELECTRICITY-Cooling'}]}}}],
             'weather': {'data_source_type': 'HISTORIC_AGGREGATION'}, 'calendar': {}}

        self.assertEqual(result, expected)

    def test_update_list(self):
        list1 = ['the', 'quick', 'brown', 'fox']
        update = ['the', 'quick', 'orange', 'bear']
        self.cph.update_list(list1, update)

        expected = ['the', 'quick', 'orange', 'bear']

        self.assertEqual(list1, expected)

        list1 = ['the', 'quick', ['brown', 'fox']]
        update = ['the', 'quick', ['orange', 'bear']]
        self.cph.update_list(list1, update)

        expected = ['the', 'quick', ['orange', 'bear']]

        self.assertEqual(list1, expected)

        list1 = [{'the': 1, 'quick': 2}, 'brown', 'fox']
        update = [{'the': 3, 'quick': 9}, 'orange', 'bear']
        self.cph.update_list(list1, update)

        expected = [{'the': 3, 'quick': 9}, 'orange', 'bear']

        self.assertEqual(list1, expected)
