from pathlib import Path
from typing import Dict

from eplus_rmd.input_file import InputFile
from eplus_rmd.output_file import OutputFile


class Translator:
    """This class reads in the input files and does the heavy lifting to write output files"""

    def __init__(self, epjson_file_path: Path):
        print(f"Reading epJSON input file at {str(epjson_file_path)}")
        self.epjson_file = InputFile(epjson_file_path)
        self.epjson_object = self.epjson_file.epjson_object
        self.json_results_object = self.epjson_file.json_results_object

        self.rmd_file_path = OutputFile(epjson_file_path)
        print(f"Will write output file to {str(self.rmd_file_path)}")

        self.rmd = {}
        self.instance = {}
        self.building = {}
        self.building_segment = {}

    @staticmethod
    def validate_input_contents(input_json: Dict):
        if 'Version' not in input_json:
            raise Exception("Did not find Version key in input file epJSON contents, aborting")
        if 'Version 1' not in input_json['Version']:
            raise Exception("Did not find \"Version 1\" key in input epJSON Version value, aborting")
        if "version_identifier" not in input_json['Version']['Version 1']:
            raise Exception("Did not find \"version_identifier\" key in input epJSON Version value, aborting")

    def get_building_name(self):
        building_input = self.epjson_object['Building']
        return list(building_input.keys())[0]

    def create_skeleton(self):
        self.building_segment = {'id': 'segment 1'}

        self.building = {'id': self.get_building_name(),
                         'notes': 'this file contains only a single building',
                         'building_segments': [self.building_segment, ]}

        self.instance = {'id': 'Only instance',
                         'notes': 'this file contains only a single instance',
                         'buildings': [self.building, ]}

        self.rmd = {'id': 'rmd_root',
                    'notes': 'generated by createRulesetModelDescription from EnergyPlus',
                    'ruleset_model_instances': [self.instance, ]}

    def add_zones(self):
        tabular_reports = self.json_results_object['TabularReports']
        zones = []
        for tabular_report in tabular_reports:
            if tabular_report['ReportName'] == 'Input Verification and Results Summary':
                tables = tabular_report['Tables']
                for table in tables:
                    if table['TableName'] == 'Zone Summary':
                        rows = table['Rows']
                        zone_names = list(rows.keys())
                        zone_names.remove('Total')
                        zone_names.remove('Conditioned Total')
                        zone_names.remove('Unconditioned Total')
                        zone_names.remove('Not Part of Total')
                        # print(zone_names)
                        cols = table['Cols']
                        volume_column = cols.index('Volume [m3]')
                        # print(volume_column)
                        for zone_name in zone_names:
                            zone = {'id': zone_name,
                                    'volume': rows[zone_name][volume_column]}
                            zones.append(zone)
                break
        self.building_segment['zones'] = zones

    def add_spaces(self):
        tabular_reports = self.json_results_object['TabularReports']
        spaces = {}
        for tabular_report in tabular_reports:
            if tabular_report['ReportName'] == 'Input Verification and Results Summary':
                tables = tabular_report['Tables']
                for table in tables:
                    if table['TableName'] == 'Space Summary':
                        rows = table['Rows']
                        space_names = list(rows.keys())
                        space_names.remove('Total')
                        space_names.remove('Conditioned Total')
                        space_names.remove('Unconditioned Total')
                        space_names.remove('Not Part of Total')
                        # print(space_names)
                        cols = table['Cols']
                        zone_name_column = cols.index('Zone Name')
                        area_column = cols.index('Area [m2]')
                        people_density_column = cols.index('People [m2 per person]')
                        for space_name in space_names:
                            floor_area = float(rows[space_name][area_column])
                            people_density = float(rows[space_name][people_density_column])
                            if people_density > 0:
                                people = floor_area / people_density
                            else:
                                people = 0
                            space = {'id': space_name, 'floor_area': floor_area, 'number_of_occupants': round(people,2)}
                            print(space, rows[space_name][zone_name_column])
                            spaces[rows[space_name][zone_name_column]] = space
        # insert the space into the corresponding Zone
        for zone in self.building_segment['zones']:
            zone['spaces'] = []
            if zone['id'] in spaces:
                zone['spaces'].append(spaces[zone['id']])

    def process(self):
        epjson = self.epjson_object
        Translator.validate_input_contents(epjson)
        # version_id = epjson['Version']['Version 1']['version_identifier']
        self.create_skeleton()
        self.add_zones()
        self.add_spaces()
        self.rmd_file_path.write(self.rmd)
