name: Run Tests

on: [push]

defaults:
  run:
    shell: bash

jobs:
  unit_tests:
    strategy:
      matrix:
        os: [ windows-latest, macos-14, macos-latest, ubuntu-20.04, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Cache Pip Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Pip Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: nosetests

#      - name: Coveralls
#        if: ${{ matrix.os == 'ubuntu-22.04' }}
#        run: coveralls --service=github
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
