name: Run All Tests

on: [push]

jobs:
  run_examples:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435  # v4.5.0
      with:
        python-version: 3.9
    - name: Install Pip Dependencies
      run: pip install -r requirements.txt
    - name: Run Tests
      run: python -m pytest
    - name: list files
      run: ls
